/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.HashSet;
import practico7.Alumno;
import practico7.Materia;

/**
 *
 * @author Mary
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {
 private HashSet <Alumno> alum;
 private HashSet <Materia> mat;
    /**
     * Creates new form FormularioInscripcion
     */
    public FormularioInscripcion(HashSet <Alumno> alum,HashSet<Materia> mat) {
        initComponents();
        this.alum=alum;
        this.mat=mat;
        agregarMateria();//llena el comboBox Materias
        agregarAlumno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlMateria = new javax.swing.JLabel();
        jlAlumno = new javax.swing.JLabel();
        ComboMateria = new javax.swing.JComboBox<>();
        ComboAlumno = new javax.swing.JComboBox<>();
        jbIncribir = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        jLabel1.setText("FORMULARIO DE INSCRIPCION");

        jlMateria.setText("Elija una materia");

        jlAlumno.setText("Elija un alumno");

        ComboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAlumnoActionPerformed(evt);
            }
        });

        jbIncribir.setText("Inscribir");
        jbIncribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncribirActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jbIncribir)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboAlumno, 0, 200, Short.MAX_VALUE)
                            .addComponent(ComboMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(280, 344, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMateria)
                    .addComponent(ComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAlumno)
                    .addComponent(ComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbIncribir)
                    .addComponent(jbSalir))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
       dispose() ;// TODO add your handling code here:
    }//GEN-LAST:event_jbSalirActionPerformed

    private void ComboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAlumnoActionPerformed

    private void jbIncribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncribirActionPerformed
        Alumno seleccionado=(Alumno)ComboAlumno.getSelectedItem();
        Materia seleccionada=(Materia)ComboMateria.getSelectedItem();
        
        seleccionado.agregarMateria(seleccionada);
    }//GEN-LAST:event_jbIncribirActionPerformed
private void agregarMateria(){
    for (Materia m1:mat){
            ComboMateria.addItem(m1);
}}
private void agregarAlumno(){
    for(Alumno a1:alum){
        ComboAlumno.addItem(a1);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> ComboAlumno;
    private javax.swing.JComboBox<Materia> ComboMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbIncribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JLabel jlMateria;
    // End of variables declaration//GEN-END:variables
}
