/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.HashSet;
import practico7.Alumno;
import practico7.Materia;

/**
 *
 * @author Mary
 */
public class Menu extends javax.swing.JFrame {

    private HashSet <Materia> materiass=new HashSet <>();
    private HashSet <Alumno> alumnoss=new HashSet <>();
    
    Materia mat=new Materia();
    Alumno al=new Alumno();
    
    
    
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jOptionPane1 = new javax.swing.JOptionPane();
        jMenuItem4 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmAltadeAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmAgregarMateria = new javax.swing.JMenuItem();
        jmInscripcion = new javax.swing.JMenu();
        jMInscripcion = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("jMenu4");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jmAlumno.setBackground(new java.awt.Color(51, 0, 255));
        jmAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jmAlumno.setText("Alumno");
        jmAlumno.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jmAltadeAlumno.setText("Alta de Alumno");
        jmAltadeAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltadeAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmAltadeAlumno);

        jMenuBar1.add(jmAlumno);

        jmMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        jmMateria.setText("Materia");
        jmMateria.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jmAgregarMateria.setText("Agregar Materia");
        jmAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmAgregarMateria);

        jMenuBar1.add(jmMateria);

        jmInscripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jmInscripcion.setText("Inscripcion");
        jmInscripcion.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMInscripcion.setText("Inscripcion");
        jMInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInscripcionActionPerformed(evt);
            }
        });
        jmInscripcion.add(jMInscripcion);

        jMenuBar1.add(jmInscripcion);

        jmSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));
        jmSalir.setText("Salir");
        jmSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jMSalir);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AgregarMateria vam=new AgregarMateria(materiass);
        vam.setVisible(true);
        escritorio.add(vam);
        escritorio.moveToFront(vam);
    }//GEN-LAST:event_jmAgregarMateriaActionPerformed

    private void jmAltadeAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltadeAlumnoActionPerformed
     escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumnos fa=new FormularioAlumnos(alumnoss);
        fa.setVisible(true);
        escritorio.add(fa);
        escritorio.moveToFront(fa);
                   
                   
    }//GEN-LAST:event_jmAltadeAlumnoActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInscripcionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioInscripcion fi=new FormularioInscripcion(alumnoss,materiass);
        fi.setVisible(true);
        escritorio.add(fi);
        escritorio.moveToFront(fi);
             
  
    }//GEN-LAST:event_jMInscripcionActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMInscripcion;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JMenuItem jmAgregarMateria;
    private javax.swing.JMenuItem jmAltadeAlumno;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmInscripcion;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
